//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.19 at 08:34:03 PM MSK 
//


package com.epam.cdp.ws.client.generate;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.epam.cdp.ws.client.generate package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.epam.cdp.ws.client.generate
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BookTicketRequest }
     * 
     */
    public BookTicketRequest createBookTicketRequest() {
        return new BookTicketRequest();
    }

    /**
     * Create an instance of {@link SoapPerson }
     * 
     */
    public SoapPerson createSoapPerson() {
        return new SoapPerson();
    }

    /**
     * Create an instance of {@link BookTicketResponse }
     * 
     */
    public BookTicketResponse createBookTicketResponse() {
        return new BookTicketResponse();
    }

    /**
     * Create an instance of {@link GetTicketRequest }
     * 
     */
    public GetTicketRequest createGetTicketRequest() {
        return new GetTicketRequest();
    }

    /**
     * Create an instance of {@link GetTicketResponse }
     * 
     */
    public GetTicketResponse createGetTicketResponse() {
        return new GetTicketResponse();
    }

    /**
     * Create an instance of {@link SoapTicket }
     * 
     */
    public SoapTicket createSoapTicket() {
        return new SoapTicket();
    }

    /**
     * Create an instance of {@link PayTicketRequest }
     * 
     */
    public PayTicketRequest createPayTicketRequest() {
        return new PayTicketRequest();
    }

    /**
     * Create an instance of {@link PayTicketResponse }
     * 
     */
    public PayTicketResponse createPayTicketResponse() {
        return new PayTicketResponse();
    }

    /**
     * Create an instance of {@link ReturnTicketRequest }
     * 
     */
    public ReturnTicketRequest createReturnTicketRequest() {
        return new ReturnTicketRequest();
    }

    /**
     * Create an instance of {@link ReturnTicketResponse }
     * 
     */
    public ReturnTicketResponse createReturnTicketResponse() {
        return new ReturnTicketResponse();
    }

}
